services:
  backend:
    container_name: 'backend'  
    build: ./backend/
    networks:
      - teste-shopper
    ports:
      - 8080:8080
    env_file:
      - ./.env
    restart: unless-stopped
  
  db:
    image: postgres:13-alpine
    container_name: teste_shopper_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=teste-shopper
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - teste-shopper
    ports:
      - 5432:5432

volumes:
  backend:
  postgres_data:

networks:
 teste-shopper:
    name: teste-shopper
    driver: bridge